"use server";
import { GetSessionParams, useSession } from "next-auth/react";
import Head from "next/head";
import { getSession } from "next-auth/react";
import GenerateBtn from "./GenerateBtn";
import { useState } from "react";
import Result from "./Result";

export default function Generate() {
  const { data: session } = useSession();
  const [resultSrc, setResultSrc] = useState("");
  function clickHandler(url: string) {
    setResultSrc(url);
  }

  if (session) {
    return (
      <>
        <Head>
          <title>Generate</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className=" flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
          <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
            <form>
              <GenerateBtn clickHandler={clickHandler}></GenerateBtn>
            </form>
            <Result imgSrc={resultSrc}></Result>
          </div>
        </main>
      </>
    );
  }
  return (
    <>
      <div>Secured Page</div>
    </>
  );
}

export async function getServerSideProps(context: GetSessionParams) {
  const session = await getSession(context);
  if (!session) {
    return {
      redirect: {
        destination: "/",
        permanent: false,
      },
    };
  }
  return {
    props: { session },
  };
}
