"use client";
import { GetSessionParams, useSession } from "next-auth/react";
import Head from "next/head";
import { getSession } from "next-auth/react";
import { useEffect, useState, useRef } from "react";
import Result from "./Result";
import { redirect } from "next/navigation";
import GenerateForm from "./GenerateForm";

export default function Generate() {
  const [resultSrc, setResultSrc] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  function startHandler() {
    setIsLoading(true);
  }
  function finishHandler(url: string) {
    setResultSrc(url);
    setIsLoading(false);
  }
  const imgRef = useRef<HTMLImageElement>(null);

  useEffect(() => {
    if (resultSrc !== "") {
      document.getElementById("imageContainer")?.focus();
    }
  }, [resultSrc]);

  // if (status === "authenticated") {
  if (true) {
    return (
      <>
        <Head>
          <title>Generate</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className=" flex min-h-[80vh] flex-col items-center ">
          <h1 className="mb-20 mt-36 text-center font-serif text-5xl font-extrabold tracking-tight text-black ">
            Create Your Logo
          </h1>
          <div></div>
          <div className="  mb-8 flex transform flex-col items-center justify-center gap-24 rounded-[12px] border-[1px]  border-[#eaeaea] bg-white drop-shadow-2xl">
            {resultSrc !== "" || isLoading ? (
              <Result
                isLoading={isLoading}
                imgSrc={resultSrc}
                imageRef={imgRef}
              ></Result>
            ) : (
              <GenerateForm
                onStart={startHandler}
                onFinish={finishHandler}
              ></GenerateForm>
            )}
          </div>
        </main>
      </>
    );
  }
}

// export async function getServerSideProps(context: GetSessionParams) {
//   const session = await getSession(context);
//   if (!session) {
//     return {
//       redirect: {
//         destination: "/",
//         permanent: false,
//       },
//     };
//   }
//   return {
//     props: { session },
//   };
// }
