import { signIn, signOut, useSession } from "next-auth/react";

import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";
import { api } from "../../trpc/react";

export default function Register() {
  const [password, setPassword] = useState("");
  const router = useRouter();
  const email = router.query.email as string;
  console.log(email);
  const mutation = api.register.register.useMutation();

  const sendRegister = async () => {
    const result = await mutation.mutateAsync({
      email: email,
      password: password,
    });
    console.log(result);
    if (true) {
      await signIn("credentials", {
        email: email,
        password: password,
      });
      void router.push("/");
    } else {
      // console.log("user already exists");
    }
  };

  const registerHandler = (event: React.MouseEvent) => {
    event.preventDefault();
    void sendRegister();
  };
  return (
    <>
      <Head>
        <title>Logo Generator</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center font-serif font-bold">
        <div>
          <h1 className="mb-20 text-center font-serif text-5xl font-extrabold  tracking-tight text-black ">
            Finish Sign Up
          </h1>

          <div className="mb-10">
            <form className="flex flex-col items-center gap-2">
              <div className="w-64 items-start">
                <label className="text-sm font-medium">Password</label>
              </div>
              <input
                placeholder="Enter Password"
                className="w-64 rounded-[6px] border-[1px] border-[#eaeaea] p-[12px] font-sans text-[14px] font-normal outline-none ring-black focus:border-black focus:ring-0 focus:ring-offset-0 "
                type="password"
                onChange={(event) => setPassword(event.target.value)}
              />
              <button
                onClick={registerHandler}
                className="w-64 rounded-md bg-[#171717] px-10 py-3 font-medium text-white no-underline transition hover:bg-[#383838]"
              >
                Continue
              </button>
            </form>
          </div>
        </div>
      </main>
    </>
  );
}
